---
abstract: 'Patterns for matching EU VAT Identification Numbers'
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-Common-VATIN
requires:
  Regexp::Common: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/rsimoes/regexp-common-vatin/issues
  homepage: https://metacpan.org/release/Regexp-Common-VATIN
  repository: git://github.com/rsimoes/regexp-common-vatin.git
version: v0.0.8
